apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    app: mysql
data:
  mysql.cnf: |-
    [mysqld]
    sql_mode = NO_ENGINE_SUBSTITUTION
  docker.cnf: |-
    [mysqld]
    # Maxwell needs that
    server_id=1
    log-bin=master
    binlog_format=row
    # Set data dir outside of docker volume
    datadir = /var/lib/mysql2/

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  type: LoadBalancer
  selector:
    app: mysql
  ports:
    - name: mysql-port
      port: 3306

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: mysql-port
          volumeMounts:
            - name: mysql-config
              mountPath: /etc/mysql/conf.d/
      volumes:
        - name: mysql-config
          configMap:
            name: mysql-config
